"""Create PO table

Revision ID: 5d38a7d5b5e6
Revises: 
Create Date: 2024-07-04 20:10:15.424105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d38a7d5b5e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('po',
    sa.Column('po_id', sa.String(length=12), nullable=False),
    sa.Column('vendor_name', sa.String(length=20), nullable=False),
    sa.Column('order_date', sa.String(length=20), nullable=False),
    sa.Column('items', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('po_id')
    )
    op.create_table('vendor',
    sa.Column('vendor_code', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('contact', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('vendor_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendor')
    op.drop_table('po')
    # ### end Alembic commands ###
